"""
Alo77 - ComfyUI Custom Nodes Collection
Main initialization file that loads all sub-nodes
"""

from .loadimages77 import NODE_CLASS_MAPPINGS as LOAD_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LOAD_DISPLAY
from .canvas77 import NODE_CLASS_MAPPINGS as CANVAS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CANVAS_DISPLAY  
from .outline77 import NODE_CLASS_MAPPINGS as OUTLINE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as OUTLINE_DISPLAY

# Combine all node mappings
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(LOAD_MAPPINGS)
NODE_CLASS_MAPPINGS.update(CANVAS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(OUTLINE_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(LOAD_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(CANVAS_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(OUTLINE_DISPLAY)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']